<?php include "app/views/layouts/header.php"; ?>
<?php
$status=$report['submission_status'] ?? 'Draft'; $editable=in_array($status,['Draft','Recalled','For Revision','Not Approved'],true); $recallable=in_array($status,['Submitted','Under Review'],true);
$ordinal=[1=>'1st',2=>'2nd',3=>'3rd',4=>'4th']; $formatDate=function($date){return $date?date('F j, Y',strtotime($date)):'';}; $formatTime=function($time){return $time?date('g:i A',strtotime($time)):'';};
?>

<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3 no-print">
    <div><span class="badge bg-<?= $status==='Approved'?'success':($editable?'secondary':'primary') ?>"><?= htmlspecialchars($status) ?></span><?php if(!empty($report['revision_notes'])): ?><span class="text-muted ms-2"><?= htmlspecialchars($report['revision_notes']) ?></span><?php endif; ?></div>
    <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="index.php?page=field_visit_logs">Back</a><?php if($canManage && $editable): ?><a class="btn btn-outline-success" href="index.php?page=edit_field_visit_log&id=<?= intval($report['id']) ?>">Edit</a><form method="post" action="index.php?page=submit_field_visit_log"><input type="hidden" name="id" value="<?= intval($report['id']) ?>"><button class="btn btn-primary">Submit</button></form><?php endif; ?><?php if($canManage && $recallable): ?><form method="post" action="index.php?page=recall_field_visit_log" onsubmit="return confirm('Recall this submission for editing?')"><input type="hidden" name="id" value="<?= intval($report['id']) ?>"><button class="btn btn-warning">Recall</button></form><?php endif; ?><button class="btn btn-dark" onclick="window.print()"><i class="bi bi-printer"></i> Print / Save PDF</button></div>
</div>

<div class="document-sheet field-visit-print">
    <table class="form-heading"><tr><td class="logo-cell"><img src="public/assets/images/evsu-official-logo.png" alt="EVSU"></td><td class="university"><strong>EASTERN VISAYAS STATE UNIVERSITY</strong><br>Tacloban City<br><b>Title of Form: WORK PLAN AND MONITORING LOG FOR FIELD VISITS</b></td><td class="meta"><b>Control No.</b> <?= htmlspecialchars($report['control_no'] ?? '') ?><br><b>Revision No.</b> <?= htmlspecialchars($report['revision_no'] ?? '') ?><br><b>Date</b> <?= htmlspecialchars($formatDate($report['form_date'] ?? '')) ?></td></tr></table>
    <h2>WORK PLAN AND MONITORING LOG FOR FIELD VISITS</h2><h3>For the <?= htmlspecialchars($ordinal[intval($report['quarter'])] ?? '') ?> quarter, <?= intval($report['report_year']) ?></h3>
    <div class="project-summary"><p><b>Program Title:</b> <?= htmlspecialchars($report['program_title'] ?? '') ?></p><p><b>Project Title:</b> <?= htmlspecialchars($report['project_title'] ?? '') ?></p><p><b>Implementing College/Department/Unit:</b> <?= htmlspecialchars($report['implementing_unit'] ?? '') ?></p><p><b>Duration:</b> <?= htmlspecialchars($formatDate($report['duration_start'] ?? '')) ?> – <?= htmlspecialchars($formatDate($report['duration_end'] ?? '')) ?> &nbsp; <b>Campus:</b> <?= htmlspecialchars($report['campus'] ?? '') ?></p></div>
    <table class="data-table"><thead><tr><th>Objectives</th><th>Activities</th><th>Date / Place / Time</th><th>Expected Output — Parameter</th><th>Expected Output — Target</th><th>Person Contacted / Position</th><th>Result of Objective</th><th>Remarks: Observations, Issues, Action Points, Comments</th></tr></thead><tbody>
    <?php foreach($items as $item): ?><tr><td><?= nl2br(htmlspecialchars($item['objectives'] ?? '')) ?></td><td><?= nl2br(htmlspecialchars($item['activities'] ?? '')) ?></td><td><?= htmlspecialchars($formatDate($item['visit_date'] ?? '')) ?><br><?= htmlspecialchars($item['place'] ?? '') ?><br><?= htmlspecialchars($formatTime($item['time_start'] ?? '')) ?><?= !empty($item['time_end'])?' – '.htmlspecialchars($formatTime($item['time_end'])):'' ?></td><td><?= nl2br(htmlspecialchars($item['expected_parameter'] ?? '')) ?></td><td><?= nl2br(htmlspecialchars($item['expected_target'] ?? '')) ?></td><td><?= htmlspecialchars($item['person_contacted'] ?? '') ?><br><?= htmlspecialchars($item['contact_position'] ?? '') ?></td><td><?= nl2br(htmlspecialchars($item['results'] ?? '')) ?></td><td><?php if(!empty($item['observations'])):?><b>Observation:</b> <?= nl2br(htmlspecialchars($item['observations'])) ?><br><?php endif; ?><?php if(!empty($item['issues'])):?><b>Issue:</b> <?= nl2br(htmlspecialchars($item['issues'])) ?><br><?php endif; ?><?php if(!empty($item['action_points'])):?><b>Action Point:</b> <?= nl2br(htmlspecialchars($item['action_points'])) ?><br><?php endif; ?><?= nl2br(htmlspecialchars($item['comments'] ?? '')) ?></td></tr><?php endforeach; ?>
    <?php if(empty($items)): ?><tr><td colspan="8">No field visit entries.</td></tr><?php endif; ?>
    </tbody></table>
    <div class="signature-grid"><div><span>Prepared by:</span><div class="signature-space"></div><b><?= htmlspecialchars($report['prepared_by'] ?? '') ?></b><br><?= htmlspecialchars($report['prepared_title'] ?? '') ?></div><div><span>Noted:</span><div class="signature-space"></div><b><?= htmlspecialchars($report['noted_by'] ?? '') ?></b><br><?= htmlspecialchars($report['noted_title'] ?? '') ?></div><div><span>Attested:</span><div class="signature-space"></div><b><?= htmlspecialchars($report['attested_by'] ?? '') ?></b><br><?= htmlspecialchars($report['attested_title'] ?? '') ?></div><div><span>Approved:</span><div class="signature-space"></div><b><?= htmlspecialchars($report['approved_by'] ?? '') ?></b><br><?= htmlspecialchars($report['approved_title'] ?? '') ?></div></div>
</div>

<style>
.document-sheet{background:#fff;color:#111;padding:24px;border:1px solid #d8dee8;overflow-x:auto}.document-sheet table{width:100%;border-collapse:collapse}.form-heading td,.data-table th,.data-table td{border:1px solid #111;padding:6px;vertical-align:top}.form-heading .logo-cell{width:80px;text-align:center}.form-heading img{width:62px}.form-heading .university{text-align:center;font-size:14px}.form-heading .university strong{font-size:18px}.form-heading .meta{width:250px;font-size:11px}.document-sheet h2,.document-sheet h3{text-align:center;margin:14px 0 4px}.document-sheet h3{font-size:16px;margin-top:0}.project-summary{font-size:11px;display:grid;grid-template-columns:1fr 1fr;gap:2px 24px;margin:12px 0}.project-summary p{margin:0}.data-table{font-size:9px;min-width:1500px}.data-table th{text-align:center;vertical-align:middle}.signature-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;text-align:center;margin-top:34px;font-size:11px}.signature-grid span{display:block;text-align:left}.signature-space{height:45px;border-bottom:1px solid #111;margin-bottom:5px}
@media print{@page{size:A4 landscape;margin:7mm}.content{padding:0!important}.page-header,.sidebar,.no-print{display:none!important}.app-shell{display:block}.document-sheet{border:0;padding:0;overflow:visible}.data-table{min-width:0;font-size:7px}.form-heading .university strong{font-size:14px}.signature-grid{break-inside:avoid;margin-top:20px}.signature-space{height:28px}}
</style>

<?php include "app/views/layouts/footer.php"; ?>
